name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cloud_functions: ^4.4.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
